# Generated by Django 3.0.3 on 2020-03-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200301_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='base_health',
        ),
        migrations.RemoveField(
            model_name='player',
            name='char_name',
        ),
    ]
