# Generated by Django 3.0.3 on 2020-03-02 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200302_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Player',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
