# Generated by Django 3.0.2 on 2020-03-09 17:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ROOM NAME', max_length=50)),
                ('desc', models.CharField(default='ROOM DESCRIPTION', max_length=500)),
                ('NORTH', models.CharField(blank=True, max_length=150)),
                ('SOUTH', models.CharField(blank=True, max_length=150)),
                ('EAST', models.CharField(blank=True, max_length=150)),
                ('WEST', models.CharField(blank=True, max_length=150)),
                ('map', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None), blank=True, size=None)),
            ],
        ),
    ]
