# Generated by Django 3.0.4 on 2020-03-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefined_world_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='EAST',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='NORTH',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='SOUTH',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='WEST',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
