# Generated by Django 3.0.4 on 2020-03-09 03:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefined_world_rooms', '0002_auto_20200308_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='EAST',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='NORTH',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='SOUTH',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='WEST',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='map',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None), blank=True, size=None),
        ),
    ]
