# Generated by Django 3.0.2 on 2020-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undefined_world_rooms', '0003_auto_20200308_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='EAST',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='NORTH',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='SOUTH',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='WEST',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
